# $NetBSD$

DISTNAME=	crass-1.0.2
CATEGORIES=	devel

MAINTAINER=	timshel@fluentdevelopment.com.au
HOMEPAGE=	https://github.com/rgrove/crass/
COMMENT=	A pure Ruby CSS 3 parser
LICENSE=	mit

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
