# $NetBSD$

DISTNAME=	chardet-0.9.0
CATEGORIES=	textproc

MAINTAINER=	timshel@fluentdevelopment.com.au
HOMEPAGE=	http://blog.vava.cn/
COMMENT=	Character encoding auto-detection in Ruby
LICENSE=	mit

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
