# $NetBSD$

DISTNAME=	gemojione-2.6.1
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME:S/gemojione/gemojione2/}
CATEGORIES=	www

MAINTAINER=	timshel@fluentdevelopment.com.au
HOMEPAGE=	http://github.com/jonathanwiesel/gemojione
COMMENT=	A gem for EmojiOne
LICENSE=	mit

DEPENDS+=	 ${RUBY_PKGPREFIX}-json>=0:../../textproc/ruby-json

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
