# $NetBSD$

DISTNAME=	nokogumbo-1.4.10
CATEGORIES=	textproc

MAINTAINER=	timshel@fluentdevelopment.com.au
HOMEPAGE=	https://github.com/rubys/nokogumbo/#readme
COMMENT=	Ruby nokogiri module for Gumbo HTML5 parser
LICENSE=	apache-2.0

DEPENDS+=       ${RUBY_PKGPREFIX}-nokogiri>=1.6.7.2<1.7:../../textproc/ruby-nokogiri

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
