# $NetBSD$

DISTNAME=	rake-compiler-1.0.3
CATEGORIES=	devel

MAINTAINER=	timshel@fluentdevelopment.com.au
HOMEPAGE=	https://github.com/rake-compiler/rake-compiler
COMMENT=	A standard and simplified way to build and package Ruby extensions using Rake
LICENSE=	mit

#DEPENDS+=	${RUBY_PKGPREFIX}-rake>=0:../../devel/ruby-rake

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
