# $NetBSD$

DISTNAME=	stringex-2.6.1
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/rsl/stringex
COMMENT=	Some (hopefully) useful extensions to Rubys String class
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
