# $NetBSD$

DISTNAME=	rouge-2.0.7
CATEGORIES=	www

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://rouge.jneen.net/
COMMENT=	Pure-ruby colorizer based on pygments
LICENSE=	mit

RUBYGEM_OPTIONS+=	--format-executable

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
