# $NetBSD$

DISTNAME=	github-markup-1.4.0
CATEGORIES=	www

MAINTAINER=	timshel@fluentdevelopment.com.au
HOMEPAGE=	https://github.com/github/markup
COMMENT=	The code Github use to render README
LICENSE=	mit

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
