# $NetBSD$

DISTNAME=	useragent-0.16.8
CATEGORIES=	textproc

MAINTAINER=	timshel@fluentdevelopment.com.au
HOMEPAGE=	https://github.com/gshutler/useragent
COMMENT=	HTTP User Agent parser
LICENSE=	mit

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
